### PR TITLE
delete config

### PR DESCRIPTION
**Pull request by stan-dot**

### CODE REVIEW

**Comment by callumforrester** [comment]
Tests that check the config is valid also need to be removed

**Review by callumforrester — APPROVED** [review]
LGTM

**Comment by tpoliaw** [comment]
There are still references to this file in docs and a(n unused) test fixture that relies on it. It would be good if the docs could be updated to either include some example config or link to somewhere some examples can be found.

**Comment by stan-dot** [comment]
hmmm, please say which fille

**Comment by tpoliaw** [comment]
Sorry, the `defaults.yaml` file

```
(⇅ 3) v3.10.13 (blueapi) /scratch/athena/blueapi (main)[*?]
❯ rg -C2 'defaults.yaml'
tests/test_config.py-53-@pytest.fixture
tests/test_config.py-54-def default_yaml(package_root: Path) -> Path:
tests/test_config.py:55:    return package_root.parent.parent / "config" / "defaults.yaml"
tests/test_config.py-56-
tests/test_config.py-57-
--
docs/how-to/configure-app.md-5-can be passed to the `blueapi` command.
docs/how-to/configure-app.md-6-
docs/how-to/configure-app.md:7:An example of this yaml file is found in `config/defaults.yaml`, which follows
docs/how-to/configure-app.md-8-the schema defined in `src/blueapi/config.py` in the `ApplicationConfig`
docs/how-to/configure-app.md-9-object.
```

**Comment by tpoliaw** [comment]
That would be good as well, but I think having examples in the docs without having to read through the code would be helpful for setting up new environments.

**Pull request merged**
