### PR TITLE
Add issue templates

### PR DESCRIPTION
**Pull request by DiamondJoseph**

### CODE REVIEW

**Comment by callumforrester** [comment]
@joeshannon The github docs provide in all caps: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by joeshannon** [comment]
To be explicit I was referring to `bug-report.md` vs `feature_request.md`.

**Comment by DiamondJoseph** [comment]
> To be explicit I was referring to `bug-report.md` vs `feature_request.md`.

I thought I'd just clicked the default buttons and only changed the content, but just tried again and they were both snake_case, not a mix of snake and kebab. I'll rename the file.

**Comment by DiamondJoseph** [comment]
> Did you mention that this was based on templates from another project?

Largely based on the dodal template

**Review by callumforrester — CHANGES_REQUESTED** [review]
I like the separation of bug report and feature request but I would favour more minimal templates, like dodal's

**Comment by DiamondJoseph** [comment]
Closing in favour of propagating up from https://github.com/DiamondLightSource/python-copier-template/pull/160

**Pull request closed without merging**
