### PR TITLE
tesitng if this quick schema checking is ok

### PR DESCRIPTION
**Pull request by stan-dot**
also doing #235 a bit fwiw?

### CODE REVIEW

**Comment by callumforrester** [comment]
What does this do that https://github.com/DiamondLightSource/blueapi/blob/main/tests/service/test_openapi.py doesn't?

**Comment by stan-dot** [comment]
the difference is this verifies that it's preserving it across time.

that python file merely checks if the schema conforms to the schema in the general sense

**Comment by joeshannon** [comment]
> the difference is this verifies that it's preserving it across time.
> 
> that python file merely checks if the schema conforms to the schema in the general sense

Could you elaborate on the "across time" part? I don't think I understand. The existing python test is also generating the schema and comparing it to the file in `docs/user/reference/openapi.yaml`.

**Comment by stan-dot** [comment]
ah sorry I was imprecise about the 'across time'. I didn't read the second test in the file closely.

**Comment by stan-dot** [comment]
I'd still make the case that the job of generating schema is different from the test.

We could keep the test file but keep it in a different job, different kind of test.

**Comment by callumforrester** [comment]
So the purpose of the test is explicitly _not_ to autogenerate a schema. If you make a change to the code that changes the schema then you, the human, should be aware of it. The change may be breaking so the most important thing is that the schema is only changed deliberately.

**Comment by stan-dot** [comment]
I fulyl agree that the human must be in the loop here

**Comment by callumforrester** [comment]
Fixed by #238 

For client generration, we would ideally like it to be in the build system rather than Github CI

**Pull request closed without merging**
