### PR TITLE
Developer tutorials and how-tos

### PR DESCRIPTION
**Pull request by callumforrester**

### CODE REVIEW

**Review by abbiemery — CHANGES_REQUESTED** [review]
Seamed to work for me. Perhaps separate the starting worker in cli and vs-code to separate bits for clarity:
```
Start worker from cli:
 --blah

Or start worker from vscode:
--blah
```

**Comment by abbiemery** [comment]
@callumforrester have you got plans for a doc somewhere to explain how to use the other cli options? Running & sending etc

**Comment by callumforrester** [comment]
It currently uses tabs to separate them, does that seem confusing?
https://diamondlightsource.github.io/blueapi/dev-tutorials/developer/tutorials/dev-run.html

**Comment by abbiemery** [comment]
> It currently uses tabs to separate them, does that seem confusing? https://diamondlightsource.github.io/blueapi/dev-tutorials/developer/tutorials/dev-run.html

Not at all thats fine, I was reading the diff so was just guessing at rendering. My bad!. Looks good then :)

**Review by abbiemery — APPROVED** [review]

**Pull request merged**
