### PR TITLE
remove pydantic pinning

### PR DESCRIPTION
**Pull request by stan-dot**

### CODE REVIEW

**Comment by DiamondJoseph** [comment]
I'm surprised it was as simple as just removing the pinning- the service still starts with our old-style BaseModels in Pydantic v2? Or are we picking up a Pydantic v1 pin from some other (dodal, ophyd-async?) dependency?

**Comment by callumforrester** [comment]
Yeah, unsure if this is happy because it just works or lack of tests...

**Comment by stan-dot** [comment]
should a test 'staging' deployment be used for this?

**Comment by callumforrester** [comment]
@stan-dot I think it's fine if someone has the time to play around with a local dev version of the server.

**Comment by stan-dot** [comment]
@callumforrester I can try this on a branch with the ViSR project is that ok?

**Comment by callumforrester** [comment]
@stan-dot I think this configuration will still install pydantic v1 because the pinned fastapi version depends on it, see #454

**Comment by stan-dot** [comment]
so it's dependent on GDA. rip
https://github.com/DiamondLightSource/blueapi/issues/454#issuecomment-2098016338

I'm unassigning myself from this issue as it does not seem resolvable in the nearest future

**Comment by DiamondJoseph** [comment]
It's also pinned in ScanSpec, dodal and other places. We need to have a mass move over

**Comment by stan-dot** [comment]
superceded by #564

**Pull request closed without merging**
