### PR TITLE
deleted

### PR DESCRIPTION
**Pull request by stan-dot**

### CODE REVIEW

**Comment by stan-dot** [comment]
Tests are failing, might just need to move those to tests as mocks

**Comment by stan-dot** [comment]
or change the name, 'startup' is misleading

**Comment by stan-dot** [comment]
alternatively we could just use all-dodal stuff
image

**Comment by callumforrester** [comment]
These are used, they produce the default, simulated environment when you run `blueapi serve` without config. I'll accept issues/PRs to modernise them/replace them with `ophyd-async`, especially now we have sim signals.

**Comment by stan-dot** [comment]
closed in favour of #484

**Pull request closed without merging**
