### PR TITLE
Configurable global plan wrapper

### PR DESCRIPTION
**Pull request by callumforrester**
Restore the global plan wrapper setting and make it configurable. Eventually we want to replace it with a combination of:
- https://github.com/DiamondLightSource/dodal/issues/576
- https://github.com/bluesky/ophyd-async/issues/314
But we need a working solution in the interim

### CODE REVIEW

**Comment by callumforrester** [comment]
@DiamondJoseph has convinced me not to do this for now, instead we are going to manually add `@attach_data_session_metadata_decorator` to all plans we want to use this for. This gives us our working interim solution.

The long-term solution is to sync the directory provider with the `RunEngine` and make detectors delay opening an HDF5 file until after a run starts, which is documented in these two issues:
- https://github.com/DiamondLightSource/dodal/issues/576
- https://github.com/bluesky/ophyd-async/issues/314

**Comment by callumforrester** [comment]
@DiamondJoseph and @keithralphs have all the plans we want wrapped been wrapped yet?

**Comment by DiamondJoseph** [comment]
IIRC Keith has a copy of `count` that has type annotations, decorators on a branch for.... i22?

**Comment by keithralphs** [comment]
Yes we made the edits for these last Tuesday in readiness for when <a thing that Joseph told me but I've since forgotten> was completed. Hopefully, these changes were made on my laptop, or they may nave since been destroyed

**Comment by keithralphs** [comment]
I can confirm that I do have the code on my laptop and it was waiting for https://github.com/DiamondLightSource/dodal/pull/590 so once a release of dodal including this is made, I can push the change to i22_bluesky that depends on the release.

**Pull request closed without merging**
